### ISSUE TITLE
[#5 Luscious] mobs in velks hitting 142...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#10]
**Message:** mobs in velks hitting 1425ac combat stility 3 warrior for max or near max constantly. 8/12 bites for max when i looked at fight vs "a shard spider". parsed 4 fights and average was 56dps, contrast with lodizal who did 43dps
 **User:** Luscious (cid: 23224, accid: 77830, client: Titanium) at 21 Aug 17 18:26 UTC
 **Location:** #zone 112, 0.000000, 513.742000, 0.000000
 **Target:** NPC a crystalline watcher (112001) spawngroup 112000

**Comment by gforce215** [comment]
Fixed on dev and live repopping velks to fix the issue
