### ISSUE TITLE
[#16 Tweena] Doom is stuck in tree now...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#21]
**Message:** Doom is stuck in tree now part of the forager.hunter cycle for sebilis keys
 **User:** Tweena (cid: 20509, accid: 77024, client: Titanium) at 23 Aug 17 13:58 UTC
 **Location:** #zone 95, 2383.990000, 3049.650000, 0.000000
 **Target:** None

**Comment by gforce215** [comment]
Hes not....not sure what she was looking at...confirmed roaming
