### ISSUE TITLE
[#19 Oakenn] The Ornate Gold Sleeve co...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#24]
**Message:** The Ornate Gold Sleeve combine doesn't seem to be working properly.  1 water flask, 1 smithy hammer, 1 gold bar, 2 high quality metal rings, 1 chainmail sleeve pattern.  I didn't try the small/large variants
 **User:** Oakenn (cid: 12863, accid: 74304, client: Titanium) at 24 Aug 17 00:13 UTC
 **Location:** #zone 202, 1375.470000, 65.514300, 0.000000
 **Target:** None

**Comment by gforce215** [comment]
Fixed, had electrum bar in the recipe /boggle
