### ISSUE TITLE
[#26 Caocao] due to a bugged teleport ...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#31]
**Message:** due to a bugged teleport and ladder problem, Zreezas the beastlord spell vendor is unreachable except by leviation or other means. 
 **User:** Caocao (cid: 26734, accid: 79160, client: Titanium) at 24 Aug 17 15:03 UTC
 **Location:** #zone 106, 0.000000, 1060.630000, 63.160300
 **Target:** NPC Zreezas (106119) spawngroup 106119

**Comment by crdunwel** [comment]
Just tried and teleporter works. The ladder is not intuitive, have to climb mostly up and face the other direction. Was able to get to Zreezas without levitate.
