### ISSUE TITLE
[#29 Zanus] Nothing is agroing in Nek...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#34]
**Message:** Nothing is agroing in Nek Forest here is a guard
 **User:** Zanus (cid: 19488, accid: 75940, client: Titanium) at 25 Aug 17 07:55 UTC
 **Location:** #zone 25, 645.026000, 2653.050000, 0.000000
 **Target:** NPC Guard Gvarr (25050) spawngroup 25050

**Comment by crdunwel** [comment]
Decaying skeletons don't aggro and the guard in the duplicate issue is lvl 16 and green mobs below lvl 19 don't aggro.
