### ISSUE TITLE
[#30 Zanus] Nothing is agroing in Nek...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#35]
**Message:** Nothing is agroing in Nek Forest here is a skeleton 
 **User:** Zanus (cid: 19488, accid: 75940, client: Titanium) at 25 Aug 17 07:55 UTC
 **Location:** #zone 25, 582.911000, 2510.050000, 0.000000
 **Target:** NPC a decaying skeleton (25322) spawngroup 25322

**Comment by fryguy503** [comment]
Duplicate #34

**Comment by crdunwel** [comment]
Decaying skeletons don't aggro and the guard in the duplicate issue is lvl 16 and green mobs below lvl 19 don't aggro.
