### ISSUE TITLE
[#35 Oakenn] the Fine Plate Collar com...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#40]
**Message:** the Fine Plate Collar combine also appears to not be working small variation works
 **User:** Oakenn (cid: 12863, accid: 74304, client: Titanium) at 27 Aug 17 15:40 UTC
 **Location:** #zone 202, 528.373000, 0.000000, 0.000000
 **Target:** None

**Comment by crdunwel** [comment]
Worked when I did combine. He may have used the wrong mold (full plate).
