### ISSUE TITLE
[#51 Gbroki] I am getting swimming ski...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#56]
**Message:** I am getting swimming skillups while sitting in Kedge.  I would expect to only get a skillup when I move.
 **User:** Gbroki (cid: 26435, accid: 78901, client: Titanium) at 31 Aug 17 12:24 UTC
 **Location:** #zone 64, 4.936450, 108.038000, 303.939000
 **Target:** None

**Comment by crdunwel** [comment]
Fixed
