### ISSUE TITLE
[#3 Gildi] weird bug, drolvargs in D...

### ISSUE THREAD

**Issue by fryguy503** [fryguy503/P2kIssues#8]
**Message:** weird bug, drolvargs in DL are amiable to a druid, but get the spell only works on animals when trying to charm..but somehow the faction is flagged as animal, doesnt happen inside KC
 **User:** Gildi (cid: 16493, accid: 69743, client: Titanium) at 21 Aug 17 15:11 UTC
 **Location:** #zone 86, 0.000000, 572.696000, 28.298200
 **Target:** NPC a drolvarg rager (86011) spawngroup 86011

**Comment by crdunwel** [comment]
![image](https://user-images.githubusercontent.com/942819/29754899-cfd68daa-8b5c-11e7-8f1f-c7b6785782b6.png)

I suppose Gildi is a halfling?
